# Generated by Django 4.2.1 on 2023-05-31 14:12

import base_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('select_role', models.CharField(choices=[('OPERATOR', 'Operator'), ('CLINIC_MANAGEMENT', 'Clinic Management')], default=None, max_length=100, null=True)),
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('avatar', models.ImageField(default='avatar.jpg', upload_to='profile_avatars')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_operator', models.BooleanField(default=False)),
                ('is_clinic_management', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('clinic_id', models.CharField(default='01615', editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('clinic_name', models.CharField(max_length=100)),
                ('clinic_url', models.URLField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=250)),
                ('country', models.CharField(choices=[('UK', 'UNITED KINGDOM'), ('IN', 'INDIA'), ('US', 'UNITED STATES OF AMERICA'), ('ES', 'SPAIN'), ('CN', 'CHINA')], default=None, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending')], default='PENDING', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicMember',
            fields=[
                ('staff_id', models.CharField(default='A924AAD', editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('IVF_COORDINATOR', 'IVF Coordinator'), ('DONOR_COORDINATOR', 'Donor Coordinator'), ('RECEPTIONIST', 'Receptionist'), ('ADMIN', 'Admin'), ('DOCTOR_PHYSICIST', 'Doctor/Physicist'), ('EMBRYOLOGY', 'Embryology'), ('NURSE', 'Nurse'), ('LABORATORY', 'Laboratory'), ('PSYCHOLOGIST_COUNSELLOR', 'Psychologist/Counsellor')], default=None, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending')], default='PENDING', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAppointment',
            fields=[
                ('appointment_id', models.CharField(default='886A4', editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('patient_first_name', models.CharField(max_length=150)),
                ('patient_last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(max_length=50)),
                ('appointment_date', models.DateField(default=django.utils.timezone.now, validators=[base_app.models.PatientAppointment.validate_date])),
                ('appointment_slot', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.clinicmember')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_id', models.CharField(default='00A7933CAE', editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('drug_name', models.CharField(max_length=200, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('generic_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
