# Generated by Django 4.2.1 on 2023-05-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='clinic_name',
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_id',
            field=models.CharField(default='5445C90BF2', editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='staff_id',
            field=models.CharField(default='ADDDBCB', editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_id',
            field=models.CharField(default='CE7E0BA998', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_id',
            field=models.CharField(default='8F737910E174', editable=False, max_length=50, unique=True),
        ),
    ]
