# Generated by Django 4.2.1 on 2023-05-31 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='mobile_number',
            new_name='contact_number',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='clinic_url',
        ),
        migrations.RemoveField(
            model_name='patientappointment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patientappointment',
            name='department',
        ),
        migrations.AddField(
            model_name='clinic',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='clinic_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.clinic'),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.clinicmember'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_id',
            field=models.CharField(default='5AD5D87090', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=100),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='clinic_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.clinic'),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='staff_id',
            field=models.CharField(default='9CD18FAC', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=100),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_id',
            field=models.CharField(default='9C050B2190', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_id',
            field=models.CharField(default='0975E05D42', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
