# Generated by Django 4.2.1 on 2023-06-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_rename_mobile_number_clinic_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drug_id',
            field=models.CharField(default='4BEF8FE4EA', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
