# Generated by Django 4.2.1 on 2023-05-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_remove_customuser_clinic_name_alter_clinic_clinic_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clinicmember',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patientappointment',
            name='id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_id',
            field=models.CharField(default='780010805D', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='staff_id',
            field=models.CharField(default='B07756E', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_id',
            field=models.CharField(default='81BF09C1EF', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_id',
            field=models.CharField(default='B6A8853C4300', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
