# Generated by Django 4.2.1 on 2023-05-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_rename_mobile_number_clinic_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=100),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_id',
            field=models.CharField(default='102F09D802', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='staff_id',
            field=models.CharField(default='0A75BA21', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_id',
            field=models.CharField(default='B506810020', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_id',
            field=models.CharField(default='A02916ABA0', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
