# Generated by Django 4.2.1 on 2023-06-15 06:23

import datetime
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_remove_clinic_clinic_url_remove_clinic_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='zipcode',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='avatar.jpg', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[150, 150], upload_to='profile_avatars'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='avatar.jpg', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[150, 150], upload_to='profile_avatars'),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='avatar.jpg', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[150, 150], upload_to='profile_avatars'),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
