# Generated by Django 4.2.1 on 2023-06-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_clientdatacollectionpool_clientpaymentdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='patient_id',
            field=models.CharField(default=None, editable=False, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='patient_age',
            field=models.IntegerField(default=0, editable=0),
        ),
    ]
