# Generated by Django 4.2.1 on 2023-05-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_remove_clinic_id_remove_clinicmember_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='clinic_id',
            field=models.CharField(default='9587B7651B', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='staff_id',
            field=models.CharField(default='89E5D87', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_id',
            field=models.CharField(default='533E6EB55A', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_id',
            field=models.CharField(default='D3820D31DBB2', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
