# Generated by Django 4.2.1 on 2023-06-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_clinic_zipcode_patientappointment_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
