# Generated by Django 4.2.1 on 2023-06-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_patientappointment_status_alter_clinic_clinic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='clinic_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='staff_id',
            field=models.CharField(default='15DA4D5F', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_id',
            field=models.CharField(default='1EC3AD37EA', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_id',
            field=models.CharField(default='3F011513E7', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
