# Generated by Django 4.2.1 on 2023-06-29 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_patientappointment_patient_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdatacollectionpool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdatacollectionpool',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clientdatacollectionpool',
            name='medical_procedure_history',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='clientdatacollectionpool',
            name='medication_history',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='clientdatacollectionpool',
            name='transactions_made',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='appointment_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='client_email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='prescription_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='total_billings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
