# Generated by Django 4.2.1 on 2023-05-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_alter_clinic_clinic_id_alter_clinicmember_staff_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_id',
            field=models.CharField(default='4C02FADD47', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='staff_id',
            field=models.CharField(default='D9E5F03', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_id',
            field=models.CharField(default='43A0600924', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_id',
            field=models.CharField(default='0CA0D8E04CAA', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
