# Generated by Django 4.2.1 on 2023-06-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_alter_clinic_clinic_id_alter_clinicmember_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicmember',
            name='staff_id',
            field=models.CharField(default='7DDC20A2', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_id',
            field=models.CharField(default='2AFFC51648', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_id',
            field=models.CharField(default='9078B16E56', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
