# Generated by Django 4.2.1 on 2023-06-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_alter_clinic_created_at_alter_clinic_zipcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
