# Generated by Django 4.2.1 on 2023-06-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_clientdatacollectionpool_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescribedmedicationmodel',
            name='for_prescription',
        ),
    ]
