# Generated by Django 4.2.1 on 2023-06-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_remove_prescribedmedication_once_per_medication_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='dosage_freq',
        ),
        migrations.AddField(
            model_name='prescribedmedication',
            name='dosage_freq',
            field=models.CharField(choices=[('ONCE_A_DAY', 'Once a day'), ('TWICE_A_DAY', 'Twice a day'), ('THRICE_A_DAY', 'Thrice a day'), ('FLEXIBLE', 'Flexible timings')], default='FLEXIBLE', max_length=250, null=True),
        ),
    ]
