# Generated by Django 4.2.1 on 2023-06-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_alter_clinicmember_staff_id_alter_drug_drug_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicmember',
            name='staff_id',
            field=models.CharField(default='1ACD4E54', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_id',
            field=models.CharField(default='77C14E8366', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
