# Generated by Django 4.2.1 on 2023-07-03 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_remove_prescribedmedicationmodel_for_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdatacollectionpool',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clientdatacollectionpool',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='clientdatacollectionpool',
            name='medical_procedure_history',
        ),
        migrations.RemoveField(
            model_name='clientdatacollectionpool',
            name='medication_history',
        ),
        migrations.RemoveField(
            model_name='clientdatacollectionpool',
            name='transactions_made',
        ),
        migrations.RemoveField(
            model_name='patientappointment',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='prescribedmedicationmodel',
            name='for_prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.prescription'),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='appointment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='client_email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='prescription_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='total_billings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='patient_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
