# Generated by Django 4.2.1 on 2023-06-15 11:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_patientappointment_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyInventory',
            fields=[
                ('drug_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('drug_name', models.CharField(max_length=250, unique=True)),
                ('generic_name', models.CharField(max_length=250)),
                ('brand_name', models.CharField(max_length=250)),
                ('drug_class', models.CharField(choices=[('ANALGESICS', 'Used for headaches, muscle pain, toothaches, menstrual pain'), ('ANTIPYRETICS', 'Used to reduce fever'), ('ANTACIDS', 'Used for heartburn, indigestion, acid reflux'), ('ANTIHISTAMINES', 'Used for allergies, itchy skin or eyes, sneezing, runny nose'), ('COUGH_AND_COLD', 'Used for cough relief, nasal congestion, sore throat'), ('TOPICAL_ANALGESICS', 'Used for muscle aches and strains, joint pain, minor injuries'), ('ANTIDIARRHEALS', 'Used for diarrhea relief'), ('DERMATOLOGICAL', 'Used for acne treatment, eczema or dermatitis management, fungal infections'), ('ORAL_CONTRACEPTIVES', 'Used for pregnancy prevention'), ('OPHTHALMIC', 'Used for eye infections, dry eyes, allergic conjunctivitis'), ('OTHER', 'Other')], default='OTHER', max_length=250)),
                ('dosage_form', models.CharField(choices=[('ORAL', 'Oral'), ('OPHTHALMIC', 'Ophthalmic'), ('INHALATION', 'Inhalation'), ('INJECTION', 'Injection'), ('TOPICAL', 'Topical'), ('OTHER', 'Other')], default='OTHER', max_length=250)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('manufacture_date', models.DateField(default=django.utils.timezone.now)),
                ('lifetime_in_months', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, default=None, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('patient_first_name', models.CharField(max_length=250)),
                ('patient_last_name', models.CharField(max_length=250)),
                ('age', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='base_app.patientappointment')),
                ('clinic_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='base_app.clinic')),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='base_app.clinicmember')),
                ('medication', models.ManyToManyField(related_name='prescriptions', to='base_app.pharmacyinventory')),
            ],
        ),
    ]
