# Generated by Django 4.2.1 on 2023-06-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_pharmacyinventory_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyinventory',
            name='drug_class',
            field=models.CharField(choices=[('ANALGESICS', 'ANALGESICS: Used for headaches, muscle pain, toothaches, menstrual pain'), ('ANTIPYRETICS', 'ANTIPYRETICS: Used to reduce fever'), ('ANTACIDS', 'ANTACIDS: Used for heartburn, indigestion, acid reflux'), ('ANTIHISTAMINES', 'ANTIHISTAMINES: Used for allergies, itchy skin or eyes, sneezing, runny nose'), ('COUGH_AND_COLD', 'COUGH_AND_COLD: Used for cough relief, nasal congestion, sore throat'), ('TOPICAL_ANALGESICS', 'TOPICAL_ANALGESICS: Used for muscle aches and strains, joint pain, minor injuries'), ('ANTIDIARRHEALS', 'ANTIDIARRHEALS: Used for diarrhea relief'), ('DERMATOLOGICAL', 'DERMATOLOGICAL: Used for acne treatment, eczema or dermatitis management, fungal infections'), ('ORAL_CONTRACEPTIVES', 'ORAL_CONTRACEPTIVES: Used for pregnancy prevention'), ('OPHTHALMIC', 'OPHTHALMIC: Used for eye infections, dry eyes, allergic conjunctivitis'), ('OTHER', 'Other')], default='OTHER', max_length=250),
        ),
    ]
