# Generated by Django 4.2.1 on 2023-07-03 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_remove_clientdatacollectionpool_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescribedmedicationmodel',
            name='for_prescription',
        ),
        migrations.AddField(
            model_name='prescribedmedicationmodel',
            name='for_appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.patientappointment'),
        ),
    ]
