# Generated by Django 4.2.1 on 2023-06-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_alter_pharmacyinventory_drug_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage_freq',
            field=models.CharField(choices=[('ONCE_A_DAY', 'Once a day'), ('TWICE_A_DAY', 'Twice a day'), ('THRICE_A_DAY', 'Thrice a day')], default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
