# Generated by Django 4.2.1 on 2023-06-16 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_remove_prescribedmedication_medication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribedmedication',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.pharmacyinventory'),
        ),
    ]
