# Generated by Django 4.2.1 on 2023-07-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_remove_prescribedmedicationmodel_for_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescribedmedicationmodel',
            name='for_appointment',
        ),
    ]
