# Generated by Django 4.2.1 on 2023-07-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_remove_prescribedmedicationmodel_for_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medications',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medications_json',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
