# Generated by Django 4.2.1 on 2023-06-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_prescription_description_prescription_dosage_freq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='dosage_freq',
            field=models.CharField(choices=[('ONCE_A_DAY', 'Once a day'), ('TWICE_A_DAY', 'Twice a day'), ('THRICE_A_DAY', 'Thrice a day')], default='ONCE_A_DAY', max_length=250, null=True),
        ),
    ]
