# Generated by Django 4.2.1 on 2023-07-04 05:55

import base_app.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_remove_prescription_medications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdatacollectionpool',
            name='medical_procedure_history',
            field=models.JSONField(blank=True, default=base_app.models.ClientDataCollectionPool.default_json_fields, null=True),
        ),
        migrations.AddField(
            model_name='clientdatacollectionpool',
            name='medication_history',
            field=models.JSONField(blank=True, default=base_app.models.ClientDataCollectionPool.default_json_fields, null=True),
        ),
        migrations.AddField(
            model_name='clientdatacollectionpool',
            name='profile_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdatacollectionpool',
            name='profile_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clientdatacollectionpool',
            name='transactions_made',
            field=models.JSONField(blank=True, default=base_app.models.ClientDataCollectionPool.default_json_fields, null=True),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='patient_id',
            field=models.CharField(default=None, editable=False, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='appointment_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='client_contact_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='client_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='client_email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='client_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='client_gender',
            field=models.CharField(default='UNDISCLOSED', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='client_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='prescription_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='total_billings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medications_json',
            field=models.JSONField(blank=True, default=base_app.models.Prescription.default_medications, null=True),
        ),
        migrations.DeleteModel(
            name='PrescribedMedicationModel',
        ),
    ]
