# Generated by Django 4.2.1 on 2023-06-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_prescribedmedication_for_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProceduresTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_choice', models.CharField(choices=[('MEDICAL_EXAMINATION', 'Medical Examination'), ('ROUTINE_CHECK_UP', 'Routine Check-up'), ('RESULT_ANALYSIS', 'Result Analysis'), ('BLOOD_TESTS', 'Blood Tests'), ('X_RAY', 'X-ray'), ('ULTRASOUND', 'Ultrasound'), ('VACCINATIONS', 'Vaccinations'), ('BIOPSY', 'Biopsy'), ('SURGERY', 'Surgery'), ('PHYSICAL_THERAPY', 'Physical Therapy'), ('HEARING_TEST', 'Hearing Test'), ('VISION_TEST', 'Vision Test'), ('CARDIAC_STRESS_TEST', 'Cardiac Stress Test'), ('ORGAN_DONATION', 'Organ Donation'), ('CONSULTATION', 'Consultation'), ('OTHER', 'Other')], default='OTHER', max_length=154, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patientappointment',
            name='procedures',
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='procedures',
            field=models.ManyToManyField(to='base_app.medicalprocedurestypes'),
        ),
    ]
