# Generated by Django 4.2.1 on 2023-07-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_clientdatacollectionpool_medical_procedure_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientappointment',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='clientdatacollectionpool',
            name='client_social_security_ID',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='patient_social_security_ID',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
