# Generated by Django 4.2.1 on 2023-06-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_rename_address_clinic_clinic_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribedmedication',
            name='total_payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
