# Generated by Django 4.2.1 on 2023-07-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_auto_20230706_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='medical_procedure_history',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='medication_history',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='transactions_made',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
