# Generated by Django 4.2.1 on 2023-06-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_prescribedmedication_total_payable_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='bill_amount',
        ),
        migrations.AddField(
            model_name='prescription',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='med_bill_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prescribedmedication',
            name='amount_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prescribedmedication',
            name='purpose',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='prescribedmedication',
            name='total_payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
