# Generated by Django 4.2.1 on 2023-06-19 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_remove_prescription_bill_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprocedurestypes',
            name='for_patient_appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.patientappointment'),
        ),
    ]
