# Generated by Django 4.2.1 on 2023-06-20 09:19

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0014_medicalprocedurestypes_for_patient_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalprocedurestypes',
            name='for_patient_appointment',
        ),
        migrations.AddField(
            model_name='pharmacyinventory',
            name='drug_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default_image.png', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[150, 150], upload_to='Drug_Stock_Images'),
        ),
    ]
