# Generated by Django 4.2.1 on 2023-06-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0015_remove_medicalprocedurestypes_for_patient_appointment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacyinventory',
            old_name='add_quantity',
            new_name='add_new_stock',
        ),
        migrations.RenameField(
            model_name='pharmacyinventory',
            old_name='unit_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='pharmacyinventory',
            old_name='total_stock_quantity',
            new_name='stock_available',
        ),
        migrations.AddField(
            model_name='pharmacyinventory',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyinventory',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyinventory',
            name='unit_type',
            field=models.CharField(choices=[('UNIT_TYPE', 'Unit Type'), ('PACK_OF_10', 'Pack of 10'), ('PACK_OF_50', 'Pack of 50')], default='UNIT_TYPE', max_length=250),
        ),
    ]
