# Generated by Django 4.2.1 on 2023-07-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0015_clientpaymentdata_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdatacollectionpool',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
