# Generated by Django 4.2.1 on 2023-06-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0016_rename_add_quantity_pharmacyinventory_add_new_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyinventory',
            name='unit_type',
            field=models.CharField(choices=[('SINGLE_UNIT', 'Single Unit'), ('PACK_OF_10', 'Pack of 10'), ('PACK_OF_50', 'Pack of 50')], default='SINGLE_UNIT', max_length=250),
        ),
    ]
