# Generated by Django 4.2.1 on 2023-07-07 07:11

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0016_clientdatacollectionpool_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdatacollectionpool',
            name='client_shipping_address',
            field=models.JSONField(blank=True, default=base_app.models.default_address, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='shipping_address',
            field=models.JSONField(blank=True, default=base_app.models.default_address, null=True),
        ),
        migrations.AlterField(
            model_name='clientdatacollectionpool',
            name='client_billing_address',
            field=models.JSONField(blank=True, default=base_app.models.default_address, null=True),
        ),
        migrations.AlterField(
            model_name='clientpaymentdata',
            name='client_billing_address',
            field=models.JSONField(blank=True, default=base_app.models.default_address, null=True),
        ),
    ]
