# Generated by Django 4.2.1 on 2023-07-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0017_clientdatacollectionpool_client_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='stripe_client_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
