# Generated by Django 4.2.1 on 2023-07-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0018_prescription_stripe_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientservicefeedback',
            old_name='doctors_support_rating',
            new_name='doctors_appointment_rating',
        ),
        migrations.RemoveField(
            model_name='clientservicefeedback',
            name='appointment_id',
        ),
        migrations.AddField(
            model_name='clientservicefeedback',
            name='customer_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
