# Generated by Django 4.2.1 on 2023-06-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0018_pharmacyinventory_stock_history_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='stripe_appointment_price_d',
            new_name='stripe_appointment_price_id',
        ),
    ]
