# Generated by Django 4.2.1 on 2023-06-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0019_rename_stripe_appointment_price_d_prescription_stripe_appointment_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='approval_status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=100),
        ),
    ]
