# Generated by Django 4.2.1 on 2023-07-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0020_delete_clientpaymentdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientservicefeedback',
            old_name='doctors_appointment_rating',
            new_name='overall_rating',
        ),
        migrations.RemoveField(
            model_name='clientservicefeedback',
            name='overall_treatment_rating',
        ),
    ]
