# Generated by Django 4.2.1 on 2023-07-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0021_rename_doctors_appointment_rating_clientservicefeedback_overall_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservicefeedback',
            name='overall_rating',
            field=models.PositiveIntegerField(blank=True, default=3, null=True),
        ),
    ]
