# Generated by Django 4.2.1 on 2023-06-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0021_prescription_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyinventory',
            name='drug_class',
            field=models.CharField(choices=[('ANALGESICS: Used for headaches, muscle pain, toothaches, menstrual pain', 'ANALGESICS'), ('ANTIPYRETICS: Used to reduce fever', 'ANTIPYRETICS'), ('ANTACIDS: Used for heartburn, indigestion, acid reflux', 'ANTACIDS'), ('ANTIHISTAMINES: Used for allergies, itchy skin or eyes, sneezing, runny nose', 'ANTIHISTAMINES'), ('COUGH_AND_COLD: Used for cough relief, nasal congestion, sore throat', 'COUGH_AND_COLD'), ('TOPICAL_ANALGESICS: Used for muscle aches and strains, joint pain, minor injuries', 'TOPICAL_ANALGESICS'), ('ANTIDIARRHEALS: Used for diarrhea relief', 'ANTIDIARRHEALS'), ('DERMATOLOGICAL: Used for acne treatment, eczema or dermatitis management, fungal infections', 'DERMATOLOGICAL'), ('ORAL_CONTRACEPTIVES: Used for pregnancy prevention', 'ORAL_CONTRACEPTIVES'), ('OPHTHALMIC: Used for eye infections, dry eyes, allergic conjunctivitis', 'OPHTHALMIC'), ('Other', 'OTHER')], default='Other', max_length=250),
        ),
    ]
