# Generated by Django 4.2.1 on 2023-06-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0022_alter_pharmacyinventory_drug_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyinventory',
            name='stripe_price_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyinventory',
            name='stripe_product_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
