# Generated by Django 4.2.1 on 2023-07-17 06:50

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0024_pharmacyinventory_drug_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchase_order_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('order', models.JSONField(blank=True, default=base_app.models.PurchaseOrder.default_file_structure, null=True)),
                ('created_by', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('authorized_by', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='PENDING', max_length=100)),
                ('request_sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
