# Generated by Django 4.2.1 on 2023-07-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0026_purchaseorder_total_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='PO_report',
            field=models.FileField(blank=True, default=None, null=True, upload_to='CSV_records'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
