# Generated by Django 4.2.1 on 2023-07-19 07:09

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0027_purchaseorder_po_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='thread_history',
            field=models.JSONField(blank=True, default=base_app.models.PurchaseOrder.default_thread, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyinventory',
            name='stock_available',
            field=models.PositiveIntegerField(default=0, help_text='available_stock'),
        ),
        migrations.AlterField(
            model_name='pharmacyinventory',
            name='stock_history',
            field=models.TextField(default='[]', help_text='stock history'),
        ),
    ]
