# Generated by Django 4.2.1 on 2023-07-19 07:13

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0028_purchaseorder_thread_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyinventory',
            name='stock_history',
            field=models.JSONField(blank=True, default=base_app.models.PharmacyInventory.default_stock_history, help_text='stock history', null=True),
        ),
    ]
