# Generated by Django 4.2.1 on 2023-07-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0029_alter_pharmacyinventory_stock_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
