# Generated by Django 4.2.1 on 2023-07-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0030_purchaseorder_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_operator',
            new_name='is_super_admin',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='select_role',
            field=models.CharField(choices=[('CLINIC_MANAGEMENT', 'Clinic Management'), ('SUPER_ADMIN', 'SuperAdmin')], default=None, max_length=100, null=True),
        ),
    ]
