# Generated by Django 4.2.1 on 2023-07-24 08:33

import base_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0031_rename_is_operator_customuser_is_super_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignmentManager',
            fields=[
                ('task_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('create_group', models.JSONField(blank=True, default=base_app.models.TaskAssignmentManager.default_json, null=True)),
                ('task', models.TextField(blank=True, default=None, null=True)),
                ('task_thread', models.JSONField(blank=True, default=base_app.models.TaskAssignmentManager.default_json, null=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MID', 'Mid'), ('LOW', 'Low')], default='LOW', max_length=100)),
                ('task_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('POSTPONED', 'Postponed'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.clinicmember')),
                ('assignor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
