# Generated by Django 4.2.1 on 2023-07-24 09:09

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0032_taskassignmentmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassignmentmanager',
            old_name='create_group',
            new_name='add_assignees',
        ),
        migrations.RemoveField(
            model_name='taskassignmentmanager',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='taskassignmentmanager',
            name='task',
        ),
        migrations.AddField(
            model_name='taskassignmentmanager',
            name='department',
            field=models.CharField(choices=[('IVF_COORDINATOR', 'IVF Coordinator'), ('DONOR_COORDINATOR', 'Donor Coordinator'), ('RECEPTIONIST', 'Receptionist'), ('ADMIN', 'Admin'), ('DOCTOR_PHYSICIST', 'Doctor/Physicist'), ('EMBRYOLOGY', 'Embryology'), ('NURSE', 'Nurse'), ('LABORATORY', 'Laboratory'), ('PSYCHOLOGIST_COUNSELLOR', 'Psychologist/Counsellor')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskassignmentmanager',
            name='sub_tasks',
            field=models.JSONField(blank=True, default=base_app.models.TaskAssignmentManager.default_json, null=True),
        ),
        migrations.AddField(
            model_name='taskassignmentmanager',
            name='task_title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskassignmentmanager',
            name='task_type',
            field=models.CharField(choices=[('GROUP', 'Group'), ('INDIVIDUAL', 'Individual')], default='INDIVIDUAL', max_length=100),
        ),
    ]
