# Generated by Django 4.2.1 on 2023-07-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0033_rename_create_group_taskassignmentmanager_add_assignees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignmentmanager',
            name='set_deadline',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='taskassignmentmanager',
            name='add_assignees',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
