# Generated by Django 4.2.1 on 2023-07-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0034_taskassignmentmanager_set_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassignmentmanager',
            name='task_type',
        ),
        migrations.AlterField(
            model_name='taskassignmentmanager',
            name='set_deadline',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
