# Generated by Django 4.2.1 on 2023-07-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0035_remove_taskassignmentmanager_task_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignmentmanager',
            name='set_deadline',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
