# Generated by Django 4.2.1 on 2023-07-27 08:45

import base_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0036_alter_taskassignmentmanager_set_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalJournal',
            fields=[
                ('note_id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(choices=[('PERSONAL', 'Personal'), ('WORK', 'Work'), ('EVENT', 'Event'), ('REMINDER', 'Reminder'), ('APPOINTMENT', 'Appointment'), ('IMPORTANT', 'Important')], default=None, max_length=100)),
                ('note_content', models.TextField(blank=True, null=True)),
                ('check_list', models.JSONField(blank=True, default=base_app.models.PersonalJournal.default_json, null=True)),
                ('reminder', models.DateTimeField(blank=True, default=None, null=True)),
                ('archive_status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
