# Generated by Django 4.2.1 on 2023-07-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0037_personaljournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaljournal',
            name='note_title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
