# Generated by Django 4.2.1 on 2023-08-02 07:29

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0038_personaljournal_note_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassignmentmanager',
            old_name='add_assignees',
            new_name='assignee',
        ),
        migrations.AddField(
            model_name='taskassignmentmanager',
            name='add_collaborators',
            field=models.JSONField(blank=True, default=base_app.models.TaskAssignmentManager.default_json, null=True),
        ),
    ]
