# Generated by Django 4.2.1 on 2023-08-09 07:06

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0039_rename_add_assignees_taskassignmentmanager_assignee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaljournal',
            name='modified_on',
        ),
        migrations.AddField(
            model_name='personaljournal',
            name='edit_timeline',
            field=models.JSONField(blank=True, default=base_app.models.PersonalJournal.default_json, null=True),
        ),
    ]
