# Generated by Django 4.2.1 on 2023-08-16 05:43

import base_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0040_remove_personaljournal_modified_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction_details', models.JSONField(default=base_app.models.POPayment.default_thread, null=True)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.purchaseorder')),
            ],
        ),
    ]
