# Generated by Django 4.2.1 on 2023-08-17 13:24

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0041_popayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_status',
            field=models.CharField(default='Unpaid', max_length=250),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='transaction_data',
            field=models.JSONField(blank=True, default=base_app.models.PurchaseOrder.default_thread, null=True),
        ),
    ]
