# Generated by Django 4.2.1 on 2023-08-18 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0042_purchaseorder_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='status',
            new_name='approval_status',
        ),
    ]
