# Generated by Django 4.2.1 on 2023-08-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0043_rename_status_purchaseorder_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyinventory',
            name='drug_class',
            field=models.CharField(choices=[('ANALGESICS: Used for headaches, muscle pain, toothaches, menstrual pain', 'ANALGESICS'), ('ANTACIDS: Used for heartburn, indigestion, acid reflux', 'ANTACIDS'), ('ANTIHISTAMINES: Used for allergies, itchy skin or eyes, sneezing, runny nose', 'ANTIHISTAMINES'), ('COUGH AND COLD: Used for cough relief, nasal congestion, sore throat', 'COUGH_AND_COLD'), ('TOPICAL ANALGESICS: Used for muscle aches and strains, joint pain, minor injuries', 'TOPICAL_ANALGESICS'), ('DERMATOLOGICAL: Used for acne treatment, eczema or dermatitis management, fungal infections', 'DERMATOLOGICAL'), ('ORAL CONTRACEPTIVES: Used for pregnancy prevention', 'ORAL_CONTRACEPTIVES'), ('OPHTHALMIC: Used for eye infections, dry eyes, allergic conjunctivitis', 'OPHTHALMIC'), ('TEST KITS: Used as diagnostic tools to detect and analyze various medical conditions or substances.', 'TEST_KITS'), ('ANTIPYRETICS: Used to reduce fever', 'ANTIPYRETICS'), ('ANTIDIARRHEALS: Used for diarrhea relief', 'ANTIDIARRHEALS'), ('Other', 'OTHER')], default='Other', max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='authorized_by',
            field=models.CharField(blank=True, default='NA', max_length=250, null=True),
        ),
    ]
