# Generated by Django 4.2.1 on 2023-08-25 09:03

import base_app.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0044_alter_pharmacyinventory_drug_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicmember',
            name='staff_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicmember',
            name='staff_date_of_birth',
            field=models.DateField(blank=True, default=None, null=True, validators=[base_app.models.ClinicMember.validate_date]),
        ),
        migrations.AddField(
            model_name='clinicmember',
            name='staff_gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNDISCLOSED', 'Undisclosed')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='staff_avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[150, 150], upload_to='profile_avatars'),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='staff_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVATE', 'Inactivate'), ('ON_NOTICE_PERIOD', 'On Notice Period')], default='INACTIVATE', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_status',
            field=models.CharField(default='UNPAID', max_length=250),
        ),
    ]
