# Generated by Django 4.2.1 on 2023-08-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0045_clinicmember_staff_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialDataEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('prescription_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('appointment_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('online_consultation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('donation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_employee_salary_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medical_supplies', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('facility_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('misc_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_fixed_budget', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('actual_monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margin_rate', models.CharField(blank=True, default=0, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicalprocedurestypes',
            name='fixed_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='patient_consent_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalprocedurestypes',
            name='procedure_choice',
            field=models.CharField(choices=[('MEDICAL_EXAMINATION', 'Medical Examination'), ('ROUTINE_CHECK_UP', 'Routine Check-up'), ('RESULT_ANALYSIS', 'Result Analysis'), ('BLOOD_TESTS', 'Blood Tests'), ('X_RAY', 'X-ray'), ('ULTRASOUND', 'Ultrasound'), ('VACCINATIONS', 'Vaccinations'), ('BIOPSY', 'Biopsy'), ('SURGERY', 'Surgery'), ('PHYSICAL_THERAPY', 'Physical Therapy'), ('HEARING_TEST', 'Hearing Test'), ('VISION_TEST', 'Vision Test'), ('CARDIAC_STRESS_TEST', 'Cardiac Stress Test'), ('ORGAN_DONATION', 'Organ Donation'), ('CONSULTATION', 'Consultation'), ('OTHER', 'Other')], default='MEDICAL_EXAMINATION', max_length=154, unique=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default=None, max_length=100, null=True),
        ),
    ]
