# Generated by Django 4.2.1 on 2023-08-25 10:31

import base_app.models
import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0046_financialdataevaluation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdataevaluation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='financialdataevaluation',
            name='month',
        ),
        migrations.AddField(
            model_name='financialdataevaluation',
            name='budget_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='financialdataevaluation',
            name='created_at',
            field=models.DateTimeField(default=base_app.models.get_current_timestamp, editable=False),
        ),
        migrations.AddField(
            model_name='financialdataevaluation',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 23, 10, 31, 20, 239213, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='financialdataevaluation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='financialdataevaluation',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
