# Generated by Django 4.2.1 on 2023-08-25 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0048_clientdatacollectionpool_client_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdataevaluation',
            name='approved_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financialdataevaluation',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 23, 11, 20, 16, 354119, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medicalprocedurestypes',
            name='procedure_choice',
            field=models.CharField(choices=[('MEDICAL_EXAMINATION', 'Medical Examination'), ('ROUTINE_CHECK_UP', 'Routine Check-up'), ('RESULT_ANALYSIS', 'Result Analysis'), ('BLOOD_TESTS', 'Blood Tests'), ('X_RAY', 'X-ray'), ('ULTRASOUND', 'Ultrasound'), ('VACCINATIONS', 'Vaccinations'), ('BIOPSY', 'Biopsy'), ('SURGERY', 'Surgery'), ('PHYSICAL_THERAPY', 'Physical Therapy'), ('HEARING_TEST', 'Hearing Test'), ('VISION_TEST', 'Vision Test'), ('CARDIAC_STRESS_TEST', 'Cardiac Stress Test'), ('ORGAN_DONATION', 'Organ Donation'), ('CONSULTATION', 'Consultation'), ('COLONOSCOPY', 'Colonoscopy'), ('MRI_SCAN', 'MRI Scan'), ('CT_SCAN', 'CT Scan'), ('PAP_SMEAR', 'Pap Smear'), ('MAMMOGRAM', 'Mammogram'), ('BONE_DENSITY_TEST', 'Bone Density Test'), ('ECG', 'Electrocardiogram (ECG or EKG)'), ('ENDOSCOPY', 'Endoscopy'), ('ALLERGY_TESTING', 'Allergy Testing'), ('SPIROMETRY', 'Spirometry (Lung Function Test)'), ('STRESS_TEST', 'Stress Test (Exercise Tolerance Test)'), ('HOLTER_MONITOR', 'Holter Monitor (24-hour ECG)'), ('SLEEP_STUDY', 'Sleep Study (Polysomnography)'), ('GASTROSCOPY', 'Gastroscopy'), ('CARDIAC_CATHETERIZATION', 'Cardiac Catheterization'), ('SKIN_BIOPSY', 'Skin Biopsy'), ('CERVICAL_BIOPSY', 'Cervical Biopsy'), ('GENETIC_TESTING', 'Genetic Testing'), ('LUMBAR_PUNCTURE', 'Lumbar Puncture (Spinal Tap)'), ('STOOL_TEST', 'Stool Test (Fecal Occult Blood Test)'), ('TREADMILL_TEST', 'Treadmill Test'), ('DOPPLER_ULTRASOUND', 'Doppler Ultrasound'), ('NUCLEAR_STRESS_TEST', 'Nuclear Stress Test'), ('OTHER', 'Other')], default='MEDICAL_EXAMINATION', max_length=154, unique=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='approval_status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=100),
        ),
    ]
