# Generated by Django 4.2.1 on 2023-08-28 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0049_financialdataevaluation_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdataevaluation',
            name='margin_rate',
        ),
        migrations.AlterField(
            model_name='financialdataevaluation',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 26, 5, 52, 22, 725718, tzinfo=datetime.timezone.utc)),
        ),
    ]
