# Generated by Django 4.2.1 on 2023-08-29 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0051_patientappointment_total_procedure_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdataevaluation',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 27, 5, 48, 45, 921013)),
        ),
    ]
