# Generated by Django 4.2.1 on 2023-08-29 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0052_alter_financialdataevaluation_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=100)),
                ('budget_title', models.CharField(blank=True, max_length=250, null=True)),
                ('budget_period_type', models.CharField(choices=[('YEARLY', 'Yearly'), ('QUARTERLY', 'Quarterly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=100)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('set_amount', models.DecimalField(decimal_places=2, default=150000, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='financialdataevaluation',
            old_name='actual_monthly_cost',
            new_name='actual_cost',
        ),
        migrations.RenameField(
            model_name='financialdataevaluation',
            old_name='medical_supplies',
            new_name='pharmacy_services',
        ),
        migrations.RenameField(
            model_name='financialdataevaluation',
            old_name='misc_expenses',
            new_name='procedure_income',
        ),
        migrations.RemoveField(
            model_name='financialdataevaluation',
            name='budget_title',
        ),
        migrations.RemoveField(
            model_name='financialdataevaluation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='financialdataevaluation',
            name='monthly_fixed_budget',
        ),
        migrations.RemoveField(
            model_name='financialdataevaluation',
            name='online_consultation',
        ),
        migrations.RemoveField(
            model_name='financialdataevaluation',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='financialdataevaluation',
            name='facility_costs',
            field=models.DecimalField(decimal_places=2, default=30000, max_digits=10),
        ),
        migrations.AddField(
            model_name='financialdataevaluation',
            name='set_budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.financialbudget'),
        ),
    ]
