# Generated by Django 4.2.1 on 2023-08-29 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0053_financialbudget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialbudget',
            name='id',
        ),
        migrations.RemoveField(
            model_name='financialdataevaluation',
            name='set_budget',
        ),
        migrations.AddField(
            model_name='financialbudget',
            name='budget_id',
            field=models.CharField(default=None, editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='financialdataevaluation',
            name='budget_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.financialbudget'),
        ),
    ]
