# Generated by Django 4.2.1 on 2023-08-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0054_remove_financialbudget_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialdataevaluation',
            old_name='prescription_income',
            new_name='pharmacy_income',
        ),
    ]
