# Generated by Django 4.2.1 on 2023-08-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0055_rename_prescription_income_financialdataevaluation_pharmacy_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialdataevaluation',
            old_name='appointment_income',
            new_name='appointment_revenue',
        ),
        migrations.RenameField(
            model_name='financialdataevaluation',
            old_name='pharmacy_income',
            new_name='employee_salary',
        ),
        migrations.RenameField(
            model_name='financialdataevaluation',
            old_name='actual_cost',
            new_name='final_total_expenditure',
        ),
        migrations.RenameField(
            model_name='financialdataevaluation',
            old_name='procedure_income',
            new_name='pharmacy_revenue',
        ),
        migrations.RenameField(
            model_name='financialdataevaluation',
            old_name='total_employee_salary_amount',
            new_name='procedure_revenue',
        ),
        migrations.AddField(
            model_name='financialdataevaluation',
            name='final_total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
