# Generated by Django 4.2.1 on 2023-08-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0056_rename_appointment_income_financialdataevaluation_appointment_revenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_slot',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='procedures',
            field=models.ManyToManyField(related_name='procedure_choice_per_patient', to='base_app.medicalprocedurestypes'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='clinic_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='consultant',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
