# Generated by Django 4.2.1 on 2023-09-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0058_alter_pharmacyinventory_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprocedurestypes',
            name='stripe_service_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='medicalprocedurestypes',
            name='stripe_service_price_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
