# Generated by Django 4.2.1 on 2023-09-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0059_medicalprocedurestypes_stripe_service_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='patient_contact_number',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
