# Generated by Django 4.2.1 on 2023-09-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0062_delete_financialdataevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(blank=True, max_length=250, null=True)),
                ('donation_date', models.DateTimeField()),
                ('donation_amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='financialbudget',
            name='approved_by',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
